version: 2.1

workflows:
  test-build:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: cimg/node:19.7.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
